trigger:
- master
- develop
- devops-test

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'


steps:
# Server
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

# Client
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js' 
  
- script: |
    cd ImportScheduler.Web/ClientApp
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'


# .NET Core NUnit-Tests
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\** 
    searchFolder: '$(System.DefaultWorkingDirectory)' 
    configuration: '$(buildConfiguration)'  


# Copy Builds to StagingDirectory
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**/$(BuildConfiguration)/**/?(*.exe|*.dll|*.pdb)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Server Files'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      ImportScheduler.Web/**/ClientApp/dist/**
      !ImportScheduler.Web/**/node_modules/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy ClientApp Files'





- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'